### ISSUE TITLE
bs-navbar-toggle error

### ISSUE THREAD

**Issue by midget2000x** [zoltan-nz/product-app#3]
After adding bootstrap, the app fails in the browser.  The console shows:

Assertion Failed: A component or helper named "bs-navbar-toggle" could not be found

**Comment by zoltan-nz** [comment]
@midget2000x thanks for the report. Have you relaunched `ember server` after adding the `ember-bootstrap` addon?

Actually, I will remove the `ember-bootstrap` addon and I will migrate this app for using `ember-cli-sass` and `ember-cli-bootstrap-sassy`, what I described here: http://yoember.com/#ember-bootstrap-sass

I feel `ember-bootstrap` is over-engineered and over-abstract bootstrap. Using plain `html` and general bootstrap is much simple.

**Comment by zoltan-nz** [comment]
@midget2000x you right. I just check, a fresh `ember install ember-bootstrap` will install a newer version of the add-on `1.0.0-alpha.3`, and the available api is changed, there isn't `bs-navbar-toggle` anymore.

**Comment by zoltan-nz** [comment]
@midget2000x `ember-bootstrap` removed and the code migrated to normal bootstrap.
fix #3 https://github.com/zoltan-nz/product-app/commit/1f99fb85a4b98eaa7249901308ed10b3f6b12a29

**Comment by midget2000x** [comment]
Thanks man!
