### ISSUE TITLE
Problem with emberx-select

### ISSUE THREAD

**Issue by docsa** [zoltan-nz/product-app#4]
I do a fresh install with git clone and npm  install.
I get : TypeError: Cannot read property 'indexOf' of undefined
    at D:\workspace\product-app\node_modules\emberx-select\index.js:14:25 

it's a bit hard for me to debug a module. 
I Tried with the latest version of  emberx-select without success.

Thanks for help

**Comment by zoltan-nz** [comment]
Hi @docsa, I'm not sure what could be the problem in your case, however, I just updated the packages on the project, hope it solves your problem also.

**Comment by docsa** [comment]
Yes !  thanks...
